### PR TITLE
Fix/2 onlyactivepr

### LINKED ISSUE #2: Do not show for completed PRs

### PR DESCRIPTION
**Pull request by jodli**
Hi!

As we still use this extension in our TFS 2018 on-premise instance I thought it would be a good idea to continue working on issues.

This fixes #2 both on frontend and backend.

Best regards
jodli

### CODE REVIEW

**Comment by cschleiden** [comment]
@jodli Oh wow, I have to apologize I completely missed this PR. Sorry about that, I'll take a look!

File: src/apply-templates/actionsCreator.ts [hunk 1]
```diff
@@ -12,14 +12,18 @@ export class ActionsCreator {
         this.actionsHub.changeSelection.invoke(selectedTemplates);
     }
 
-    initialize(): void {
-        new TemplateStoreService().getTemplates().then(
-            templates => {
-                this.actionsHub.initialize.invoke(templates);
-            },
-            error => {
+    initialize(pullRequest: IActionPullRequest): void {
```
Comment (cschleiden) [inline src/apply-templates/actionsCreator.ts]: I think it might be better to make these calls in parallel:

```ts
initialize(pullRequest: IActionPullRequest): void {
  Promise.all([
    new TemplateStoreService().getTemplates(),
    new ApplyTemplateService().getStatus(pullRequest)
  ].then([templates, prStatus] => {
    this.actionsHub.initializeTemplates.invoke(templates);
    this.actionsHub.initializeStatus.invoke(prStatus);
  }, error => {
    this.actionsHub.changeMode.invoke(Mode.Error);
  });
}
```

**Comment by cschleiden** [comment]
Thanks, I'll update the extension in the next couple days

**Comment by cschleiden** [comment]
@jodli I've published the updated extension, thanks for your contribution!
